[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NETLIFY_USE_PNPM = "true"

[build]
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200